### ISSUE TITLE
change the port and db type 

### ISSUE THREAD

**Issue by MrSalman333** [zzorica/helm-charts#20]
hi, thanks for the great work. 

I was trying to use your chart. however I want to connect to an external postgres database. in the templates I found out the port is hardcoded and there is no way to change it. however the docker image support postgres and mysql

**Comment by zzorica** [comment]
Terribly sorryy @MrSalman333 as I overlooked this one for "quite" some time 😄

**Comment by marcwittke** [comment]
It looks like there are still some mysql/mariadb hard coded bits, e.g.:

https://github.com/zzorica/helm-charts/blob/2049c37912b6a22b14afd09225974744ea457fde/charts/freescout/templates/deployment.yaml#L34

**Comment by PatrickHuetter** [comment]
+1 - the hardcoded mysql check prevents usigng pgsql.
