### ISSUE TITLE
Can't find secret freescout-db

### ISSUE THREAD

**Issue by Pickachu1812** [zzorica/helm-charts#9]
I had en error with external database and password for it in values

Pod cant find secret freescout-db. 
He's trying to find it, because there is code in the template of deployment:
`- name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: {{ .Values.externalDatabase.existingSecret.secretName | default (printf "%s-%s" .Release.Name "db") }}
                key: {{ .Values.externalDatabase.existingSecret.passwordKey | default "db-password" }}
`
Name of the secret is freescout-db

But in the template secret-db.yaml the name of secret is:
`name: {{ printf "%s-%s" .Release.Name "mariadb"  }}`
freescout-mariadb
That's why pod can't find it

**Comment by FERNDIO-GITHUB** [comment]
I'm having the same issue, being forced to use k8s secrets to avoid this

**Comment by zzorica** [comment]
@Pickachu1812 @FERNDIO-GITHUB 

Thank both of you on catching this one!
